<?xml version="1.0" encoding="UTF-8"?>
<project name="ci-jenkins-demo" default="build" basedir=".">

    <property name="src.dir" value="src/main/java"/>
    <property name="test.dir" value="src/test/java"/>
    <property name="build.dir" value="ant-build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="test-classes.dir" value="${build.dir}/test-classes"/>
    <property name="dist.dir" value="${build.dir}/dist"/>
    <property name="jar.name" value="ci-jenkins-demo-1.0.0.jar"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="init">
        <mkdir dir="${classes.dir}"/>
        <mkdir dir="${test-classes.dir}"/>
        <mkdir dir="${dist.dir}"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="${src.dir}" destdir="${classes.dir}" includeantruntime="false"/>
    </target>

    <target name="compile-test" depends="compile">
        <javac srcdir="${test.dir}" destdir="${test-classes.dir}" includeantruntime="false">
            <classpath>
                <pathelement location="${classes.dir}"/>
            </classpath>
        </javac>
    </target>

    <target name="test" depends="compile-test">
        <java classname="com.vit.demo.AppTest" fork="true" failonerror="true">
            <classpath>
                <pathelement location="${classes.dir}"/>
                <pathelement location="${test-classes.dir}"/>
            </classpath>
        </java>
        <echo message="ANT BUILD SUCCESSFUL"/>
    </target>

    <target name="jar" depends="test">
        <jar destfile="${dist.dir}/${jar.name}" basedir="${classes.dir}">
            <manifest>
                <attribute name="Main-Class" value="com.vit.demo.App"/>
            </manifest>
        </jar>
    </target>

    <target name="build" depends="jar"/>

</project>
