pipeline {
    agent any

    tools {
        jdk 'JDK-21'
        maven 'Maven-3'
    }

    environment {
        PROJECT_DIR = 'jenkins-tomcat-demo'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Downloading source code from GitHub'
                git branch: 'main',
                    url: 'https://github.com/yashikadhawral/DevOps.git'
            }
        }

        stage('Compile') {
            steps {
                dir("${PROJECT_DIR}") {
                    echo 'Compiling Java application'
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${PROJECT_DIR}") {
                    echo 'Executing JUnit tests'
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir("${PROJECT_DIR}") {
                    echo 'Creating WAR file'
                    bat 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.war',
                        fingerprint: true
                }
            }
        }

        stage('Deploy') {
            steps {
                dir("${PROJECT_DIR}") {
                    echo 'Deploying application to Tomcat'
                    bat '''
                        copy /Y target\\jenkins-demo.war ^
                        "C:\\Program Files\\Apache Software Foundation\\Tomcat 11.0\\webapps\\jenkins-demo.war"
                    '''
                }
            }
        }

        stage('Verify') {
            steps {
                echo 'Checking deployed application'
                bat '''
                    curl.exe --fail ^
                    http://localhost:8081/jenkins-demo/
                '''
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true,
                testResults: "${PROJECT_DIR}/target/surefire-reports/*.xml"
        }
        success {
            echo 'CI/CD PIPELINE SUCCESSFUL'
        }
        failure {
            echo 'CI/CD PIPELINE FAILED'
        }
    }
}
